### ISSUE TITLE
204 Error when serving a file from a different folder

### ISSUE THREAD

**Issue by mdevDE** [fastify/fastify-static#232] opened 2021-09-13 08:20 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.21.0

### Plugin version

4.2.3

### Node.js version

12.22.5

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

10.15.7

### Description

Hi there,

When I serve files and images after checking an access token I get an Error 204. The files have been checked for existence and accessibility. They will be served as expected.

[1631519821990] INFO (45359 on xxxxxxxxx): request completed
    res: {
      "statusCode": 200
    }
    responseTime: 4220.000035047531
    reqId: "req-8"
[1631519821990] ERROR (45359 on xxxxxxxxx): Promise may not be fulfilled with 'undefined' when statusCode is not 204
    reqId: "req-8"
    err: {
      "type": "FastifyError",
      "message": "Promise may not be fulfilled with 'undefined' when statusCode is not 204",
      "stack":
          FastifyError: Promise may not be fulfilled with 'undefined' when statusCode is not 204
              at /Volumes/Data/DevAPP/api/backend/node_modules/fastify/lib/wrapThenable.js:30:30
              at processTicksAndRejections (internal/process/task_queues.js:97:5)
      "name": "FastifyError",
      "code": "FST_ERR_PROMISE_NOT_FULFILLED",
      "statusCode": 500
    }

### Steps to Reproduce

fastify.get ('/*', async (request, reply) => {
      const token = await checkAccessToken(request, reply)
      if(token.valid){
        ...
        return reply.sendFile(filePath, uploadPath)
        }
   ...
}

**Comment by mcollina** [comment] 2021-09-13 08:23
Can you provide steps to reproduce? Code that we can run without changes to reproduce the problem.

**Comment by mdevDE** [comment] 2021-09-13 08:31
I just tried to hard code the file path and folder with the same Error 204 as a result

fastify.get ('/*',(_request: any, reply: any) => {
    const  file = '0beec0f6-b98f-11ea-87e4-288e51e9a064/resources/clients/1613ae9e-10a1-11ea-9be7-c4b301cd9aa1/79f135d758e25d6417442d2578b3cfab081c8f09c6a51382.png'
        const folder = '/Volumes/Data/dist/uploads/'
        return reply.sendFile(file, folder)
    })


==> resulting in
[1631521674889] INFO (45932 on xxxxxxxxx): request completed
    res: {
      "statusCode": 200
    }
    responseTime: 2052.232829988003
    reqId: "req-6"
[1631521674889] ERROR (45932 on xxxxxxxxx): Promise may not be fulfilled with 'undefined' when statusCode is not 204
    reqId: "req-6"
    err: {
      "type": "FastifyError",
      "message": "Promise may not be fulfilled with 'undefined' when statusCode is not 204",
      "stack":
          FastifyError: Promise may not be fulfilled with 'undefined' when statusCode is not 204
              at /Volumes/Data/DevAPP/api/backend/node_modules/fastify/lib/wrapThenable.js:30:30
              at ServerResponse.<anonymous> (/Volumes/Data/DevAPP/api/backend/node_modules/fastify/lib/reply.js:341:7)
              at ServerResponse.<anonymous> (/Volumes/Data/DevAPP/api/backend/node_modules/readable-stream/lib/internal/streams/end-of-stream.js:17:14)
              at ServerResponse.onfinish (/Volumes/Data/DevAPP/api/backend/node_modules/readable-stream/lib/internal/streams/end-of-stream.js:43:29)
              at ServerResponse.emit (events.js:326:22)
              at onFinish (_http_outgoing.js:735:10)
              at afterWrite (_stream_writable.js:490:5)
              at afterWriteTick (_stream_writable.js:477:10)
              at processTicksAndRejections (internal/process/task_queues.js:83:21)
      "name": "FastifyError",
      "code": "FST_ERR_PROMISE_NOT_FULFILLED",
      "statusCode": 500
    }

**Comment by mcollina** [comment] 2021-09-13 08:43
**please provide a full and complete example to reproduce your problem, otherwise we cannot help**.

**Comment by mdevDE** [comment] 2021-09-13 09:20
Hi Matteo, 
I hope this helps

// Require the framework and instantiate it
const fastify = require('fastify')({ logger          :  { prettyPrint : true } })
const path    = require('path')
const fs      = require('fs')

fastify.register(require('fastify-static'), {
  root: path.join(__dirname, 'uploads'),
  prefix: '/public/', // optional: default '/'
})

fastify.get('/*', function (req, reply) {
  const file   = '0beec0f6-b98f-11ea-87e4-288e51e9a064/resources/clients/1613ae9e-10a1-11ea-9be7-c4b301cd9aa1/79f135d758e25d6417442d2578b3cfab081c8f09c6a51382.png'
  const folder = '/Volumes/Data/DevAPP/api/test/uploads/'

  // get file/dir stats
  const fileStat = fs.statSync(folder+file)
  // get size
  const size     = fileStat.size/1024/1024 //MB
  // check if this is a directory
  const isDir    = fileStat.isDirectory()
  // check if this is a file
  const isFile   = fileStat.isFile()
  console.log('check file', size, isDir, isFile)
  return reply.sendFile(file, folder)
})

// Run the server!
const start = async () => {
  try {
    await fastify.listen(3000)
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}
start()

==> output

[1631524714248] INFO (48023 on xxxxxxxxxxxxx): incoming request
    req: {
      "method": "GET",
      "url": "/",
      "hostname": "127.0.0.1:3000",
      "remoteAddress": "127.0.0.1",
      "remotePort": 51778
    }
    reqId: "req-1"
---------------------
File Check
0.11778640747070312 false true
---------------------
[1631524715740] ERROR (48023 on xxxxxxxxxxxxx): Promise may not be fulfilled with 'undefined' when statusCode is not 204
    reqId: "req-1"
    err: {
      "type": "FastifyError",
      "message": "Promise may not be fulfilled with 'undefined' when statusCode is not 204",
      "stack":
          FastifyError: Promise may not be fulfilled with 'undefined' when statusCode is not 204
              at /Volumes/Data/DevAPP/api/test/node_modules/fastify/lib/wrapThenable.js:30:30
              at ServerResponse.<anonymous> (/Volumes/Data/DevAPP/api/test/node_modules/fastify/lib/reply.js:341:7)
              at ServerResponse.<anonymous> (/Volumes/Data/DevAPP/api/test/node_modules/readable-stream/lib/internal/streams/end-of-stream.js:17:14)
              at ServerResponse.onclose (/Volumes/Data/DevAPP/api/test/node_modules/readable-stream/lib/internal/streams/end-of-stream.js:68:23)
              at ServerResponse.emit (events.js:326:22)
              at Socket.onServerResponseClose (_http_server.js:209:44)
              at Socket.emit (events.js:326:22)
              at TCP.<anonymous> (net.js:675:12)
              at TCP.callbackTrampoline (internal/async_hooks.js:126:14)
      "name": "FastifyError",
      "code": "FST_ERR_PROMISE_NOT_FULFILLED",
      "statusCode": 500
    }
[1631524715744] INFO (48023 on xxxxxxxxxxxxx): stream closed prematurely
    res: {
      "statusCode": 200
    }
    reqId: "req-1"

**Comment by mcollina** [comment] 2021-09-13 12:33
// Require the framework and instantiate it
const fastify = require('fastify')({ logger          :  { prettyPrint : true } })
const path    = require('path')
const fs      = require('fs')

fastify.register(require('fastify-static'), {
  root: path.join(__dirname, 'uploads'),
  prefix: '/public/', // optional: default '/'
})

fastify.get('/*', function (req, reply) {
  const file   = '0beec0f6-b98f-11ea-87e4-288e51e9a064/resources/clients/1613ae9e-10a1-11ea-9be7-c4b301cd9aa1/79f135d758e25d6417442d2578b3cfab081c8f09c6a51382.png'
  const folder = '/Volumes/Data/DevAPP/api/test/uploads/'

  // get file/dir stats
  const fileStat = fs.statSync(folder+file)
  // get size
  const size     = fileStat.size/1024/1024 //MB
  // check if this is a directory
  const isDir    = fileStat.isDirectory()
  // check if this is a file
  const isFile   = fileStat.isFile()
  console.log('check file', size, isDir, isFile)
  reply.sendFile(file, folder)
  return reply // this will do the trick
})

// Run the server!
const start = async () => {
  try {
    await fastify.listen(3000)
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}
start()

**Comment by adrian-branescu** [comment] 2021-09-16 11:49
Hi, @mcollina 
It always replicates on _fastify_ **v3.21.0** and **v3.21.1**, but **not** on **v30.0.2** so I suppose that it was introduced by one of these commits https://github.com/fastify/fastify/compare/v3.20.2...v3.21.0

My scenario is pretty basic, I just use the _sendFile_ reply decoration of the _fastify-static_ plugin in a route handler. 
The only differences from the above scenario is that I set _serve_ to _false_ and my route handler is an async function.

```javascript
import fastify from 'fastify';
import staticPlugin from 'fastify-static';

const endpoint = fastify({/* some config */});
endpoint.register(staticPlugin, {
    root: 'changeme/serve/dir',
    serve: false,
    cacheControl: true,
    etag: true,
    immutable: true,
    maxAge: '1d'
});

// handler:
async (request, reply) => {

    const physicalPath = 'some/file/path/relative/to/serve/dir';

    reply.sendFile(physicalPath);
    return reply;
}
```

Note that the files are successfully served, only that the log is full of _FST_ERR_PROMISE_NOT_FULFILLED_, one for each file.

As far as I followed the flow it seems the problem is that the Promise returned by the async route handler:
https://github.com/fastify/fastify/blob/main/lib/handleRequest.js#L138
resolves before _reply[kReplySent]_ being set to _true_ (if it's ever set):
https://github.com/fastify/fastify/blob/main/lib/wrapThenable.js#L30

I'm not sure who is supposed to set that flag when the body of the reply is a stream. Anyway, this is where I stopped digging:
https://github.com/fastify/fastify/blob/main/lib/reply.js#L425

**Comment by mcollina** [comment] 2021-09-16 13:15
I have a feeling this is due to https://github.com/fastify/fastify/commit/e0ca9c440c3d8e160132f75dca748edec6418830.

**Comment by mcollina** [comment] 2021-09-16 13:16
@adrian-branescu a PR to Fastify would be awesome, thanks for the analysis so far.

**Comment by adrian-branescu** [comment] 2021-09-16 15:07
@mcollina  done https://github.com/fastify/fastify/pull/3318

**Comment by mcollina** [comment] 2021-09-25 07:33
This was fixed in Fastify.

**Closed** 2021-09-25 07:33 UTC
