### ISSUE TITLE
Not working after update

### ISSUE THREAD

**Issue by MarianoFacundoArch** [fastify/fastify-static#350] opened 2022-12-26 17:18 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.10.2

### Plugin version

6.6.0

### Node.js version

16.17.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.1

### Description

I just updated the entire project to fastify 4 and fastify-static 6.6.0 when I noticed the sendFile stopped working.
I tried everything, but it's not working.

The lines of code being used are:

`            reply.sendFile(
              path.basename(localFilePath),
              path.dirname(localFilePath)
            );`

I tried to see if the problem was when using a different path that the constructor specified one, but it was not either.

Everytime I do the sendfile I get a blank response and not the file.

### Steps to Reproduce

`            reply.sendFile(
              path.basename(localFilePath),
              path.dirname(localFilePath)
            );`

### Expected Behavior

The file is sent

**Comment by climba03003** [comment] 2022-12-26 17:41
You need to provide a run-able code in order for us to debug the issue.
A single line of code do not helps for debugging or spot the error.

**Comment by MarianoFacundoArch** [comment] 2022-12-26 17:54
I found the issue,
It happens when using reply.sendfile without an await in front if the route handler is async.

I.E.:
`
app.get('/demo', async (req,reply)=> {
 sendFile("file.html","/root/path")
})`

Before it used to work, now await is needed for it to work before sendFile.

Is this a bug? Is this intended?

**Comment by climba03003** [comment] 2022-12-26 18:03
I am closing it as it is not a bug.

Yes, it is intended. Please read the migration guide.
https://github.com/fastify/fastify/blob/main/docs/Guides/Migration-Guide-V4.md#need-to-return-reply-to-signal-a-fork-of-the-promise-chain

**Closed by climba03003** 2022-12-26 18:03 UTC
