### ISSUE TITLE
EMFILE: too many open files

### ISSUE THREAD

**Issue by mangodoapps** [fastify/fastify-static#472] opened 2024-09-12 12:54 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.0

### Plugin version

6.12.0

### Node.js version

21.5.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

Server 2019 Datacenter

### Description

I have been getting the 'EMFILE: too many open files, open '......mp4'' error for 1-2 months now, and I have researched all possible solutions but haven't been able to fix it. From my research, it seems that files opened with 'fs' need to be closed using 'fs.close', but I tried to examine the fastify/static plugin and couldn't understand it. Do you think there might be a problem related to this in the package, or is there a solution?

### Expected Behavior

I am waiting for a solution to the problem.

**Comment by mcollina** [comment] 2024-09-12 12:59
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by Uzlopak** [comment] 2024-09-12 13:01
Maybe you are chose the wront technology. You are basically reporting that file handlers are exhausted. You can either increase the file handler limit or you need.to change your technology tor serving files. E.g. using nginx and if you need permissions or so, stream them behind like a reverse proxy.

**Comment by mangodoapps** [comment] 2024-09-12 13:37
@mcollina

The error occurs irregularly. Sometimes after 4 days, sometimes after 7 days. Since this is a private project, I cannot share the code, but the error doesn't appear as soon as the software runs.

@Uzlopak

I don't think it's due to the wrong technology because this package delivers what's needed, it just seem like there's a bug. Since my software displays a large number of files on a minute basis, I reported the bug thinking that maybe no one else is handling such high-flow static file display like I am. If I need to switch to a different technology, of course, I will, but I want to know for sure whether there's a bug or not. Switching to a new technology will require extra effort.

**Comment by jsumners** [comment] 2024-09-12 14:21
Closing due to lack of cooperation.

**Closed** 2024-09-12 14:21 UTC
